{-symbol-placement
symbol-spacing
symbol-avoid-edges
symbol-sort-key
symbol-z-order
icon-allow-overlap
icon-overlap
icon-ignore-placement
icon-optional
icon-rotation-alignment
icon-size
icon-text-fit
icon-text-fit-padding
icon-image
icon-rotate
icon-padding
icon-keep-upright
icon-offset
icon-anchor
icon-pitch-alignment
text-pitch-alignment
text-rotation-alignment

text-font
text-size
text-max-width
text-line-height
text-letter-spacing
text-justify
text-radial-offset
text-variable-anchor
text-variable-anchor-offset
text-anchor
text-max-angle
text-writing-mode
text-rotate
text-padding
text-keep-upright
text-transform
text-offset
text-allow-overlap
text-overlap
text-ignore-placement
text-optional
visibility
icon-opacity
icon-color
icon-halo-color
icon-halo-width
icon-halo-blur
icon-translate
icon-translate-anchor
text-opacity
text-color
text-halo-color
text-halo-width
text-halo-blur
text-translate
text-translate-anchor-}
